server:
  port: 7001

system:
    appId: bibleapp
    token: bWlubGlhCg==

# SPRING PROFILES
spring:
    profile: dev
    application:
        name: 应用
    http:
        encoding.charset: UTF-8
        encoding.enable: true
        encoding.force: true

    datasource:
        name:
#        driver-class-name: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        driverClassName: net.sf.log4jdbc.DriverSpy
        url: jdbc:log4jdbc:mysql://rm-bp1v94c921ols1ne60o.mysql.rds.aliyuncs.com/yuncard_dev?createDatabaseIfNotExist=true&useUnicode=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&verifyServerCertificate=false&useSSL=false&sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false&allowMultiQueries=true
        username: root
        password: yuncard123!
#        使用druid数据源
#        type: com.alibaba.druid.pool.DruidDataSource
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        continue-on-error: true
        initialize: true

    redis:
        database: 0
        host: 47.93.48.243
        password: yunka123
        pool:
            max-active: 8
            max-idle: 8
            max-wait: -1
            min-idle: 0
        port: 6379
        timeout: 0

system.security.jwt:
#  tokenExpirationTime: 15 # Number of minutes
  tokenExpirationTime: 604800 # Number of minutes
  refreshTokenExpTime: 604800 # Minutes
  tokenIssuer: http://minlia.com
  tokenSigningKey: minlia8EV6Hy5RMFK4EEACIDAwQus
  
#spring.datasource:
#  url: "jdbc:h2:mem:testdb"
#  driverClassName: org.h2.Driver
#  username: sa
#  password: ""
#  data: "classpath*:data.sql"
#spring.jpa:
#  database-platform: org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled: true
swagger:
    title: ${spring.application.name}接口
    description: ${spring.application.name}接口
    version: 1.0
    contact: cloud@minlia.com
    path: /api/.*
    redirect: true

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml