spring:
    profile: dev
    application:
        name: redisapp
    session:
        store-type: redis

    redis:
        database: 0
        host: 47.93.48.243
        password: xxxxxx
        pool:
            max-active: 8
            max-idle: 8
            max-wait: -1
            min-idle: 0
        port: 6379
        timeout: 0